### PR TITLE
fix: Allow errors bubble up to the caller

### LINKED ISSUE #56: Uncaught exceptions in `lib/index.js`
In `lib/index.js`, there is missing a call to `.catch()` for the `driver.executeAsyncScript()` promise chain. When `executeAsyncScript` throws an exception, it is unhandled and will crash Node.

A fix seems to be to just tag `.catch(err => {reject(err)});` onto the `executeAsyncScript()` promise chain in `lib/index.js`.

### PR DESCRIPTION
**Pull request by stephenmathieson**
This patch prevents unhandled Promise rejections from crashing the process by allowing the caller to handle them instead.

To properly call `Builder#analyze()`, you **SHOULD** change your code from:

```js
builder.analyze(function(results) {
  // Do something with results
});
```

To:

```js
builder.analyze(function(err, results) {
  if (err) {
    // handle error
  }

  // Do something with results
});
```

However, if you do not update your code, `axe-webdriverjs` will continue to function the same way (for the time being), but will print a deprecation warning to `stderr`. ⚠️ This functionality will be removed in the next major release.⚠️

Additionally, when using the Promise returned by `Builder#analyze()`, you **SHOULD** add a `.catch()` block to handle the possible rejection. For example:

```js
builder
  .analyze()
  .then(results => {
    // Do something with results
  })
  .catch(err => {
    // handle error
  });
```

If neither a `.catch()` block or a callback are provided, an unhandled rejection will occur and the Node process will crash. ☠️

NOTE: when using a Promise _and_ a callback, the Promise will never be rejected. Either the callback will be provided the error, or the error will be thrown instead. This ensures we don't require users to handle the same error twice.

New tests have been added ensuring this behavior works as expected. Additionally, all old tests have been migrated to the new API, which should help encourage users to do the same.

Fixes #56.
Duplicates #79.

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: @wilcofiers

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -128,7 +132,13 @@ AxeBuilder.prototype.analyze = function(callback) {
     config = this._config,
     source = this._source;
 
-  return new Promise(function(resolve) {
+  // Check if the provided `callback` uses the old argument signature (an arity of 1). If it does, provide a helpful deprecation warning.
+  var isOldAPI = callback && callback.length === 1;
+  if (isOldAPI) {
+    deprecate('When using the callback API, you must handle errors');
```
Comment (WilcoFiers) [inline lib/index.js]: I suggest: "Error must be handled as the first argument of axe.analyze. See: https://github.com/dequelabs/axe-webdriverjs/pull/83"
